create table if not exists public.backtest_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  code text not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'complete', 'failed')),
  result_json jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists backtest_requests_user_created_idx
on public.backtest_requests (user_id, created_at desc);

alter table public.backtest_requests enable row level security;
grant select, insert on table public.backtest_requests to authenticated;
grant select, update on table public.backtest_requests to service_role;

drop policy if exists "users read own backtest requests" on public.backtest_requests;
create policy "users read own backtest requests"
on public.backtest_requests for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "users create own backtest requests" on public.backtest_requests;
create policy "users create own backtest requests"
on public.backtest_requests for insert to authenticated
with check ((select auth.uid()) = user_id);
