create table if not exists public.backtest_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  code text not null,
  up_target_percent double precision,
  down_target_percent double precision,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'complete', 'failed')),
  result_json jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.backtest_requests
drop constraint if exists backtest_requests_up_target_percent_check;
alter table public.backtest_requests
add constraint backtest_requests_up_target_percent_check
check (up_target_percent is null or up_target_percent > 0 and up_target_percent <= 100);
alter table public.backtest_requests
drop constraint if exists backtest_requests_down_target_percent_check;
alter table public.backtest_requests
add constraint backtest_requests_down_target_percent_check
check (down_target_percent is null or down_target_percent > 0 and down_target_percent <= 100);

create index if not exists backtest_requests_user_created_idx
on public.backtest_requests (user_id, created_at desc);

alter table public.backtest_requests enable row level security;
grant select, insert on table public.backtest_requests to authenticated;
grant select, update on table public.backtest_requests to service_role;

drop policy if exists "users read own backtest requests" on public.backtest_requests;
create policy "users read own backtest requests"
on public.backtest_requests for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "users create own backtest requests" on public.backtest_requests;
create policy "users create own backtest requests"
on public.backtest_requests for insert to authenticated
with check ((select auth.uid()) = user_id);

