-- StockAI Android v0.3.0: separate expectation rules, candidate list, and requested backtests.
alter table public.screening_preferences
add column if not exists expectation_mode text not null default 'auto';
alter table public.screening_preferences
add column if not exists expectation_genre_id text;
alter table public.screening_preferences
add column if not exists expectation_manual_logic text not null default 'all';
alter table public.screening_preferences
add column if not exists expectation_manual_conditions jsonb not null default '[]'::jsonb;
alter table public.screening_preferences
drop constraint if exists manual_condition_limit;
alter table public.screening_preferences
add constraint manual_condition_limit
check (jsonb_array_length(manual_conditions) <= 32);

create table if not exists public.screening_candidates (
  pool_date date not null,
  code text not null,
  updated_at timestamptz not null default now(),
  primary key (pool_date, code)
);
create index if not exists screening_candidates_date_idx
on public.screening_candidates (pool_date desc, code);
alter table public.screening_candidates enable row level security;
grant select on table public.screening_candidates to authenticated;
grant select, insert, delete on table public.screening_candidates to service_role;
drop policy if exists "authenticated users read candidate pool"
on public.screening_candidates;
create policy "authenticated users read candidate pool"
on public.screening_candidates for select to authenticated using (true);

create table if not exists public.backtest_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  code text not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'complete', 'failed')),
  result_json jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists backtest_requests_user_created_idx
on public.backtest_requests (user_id, created_at desc);
alter table public.backtest_requests enable row level security;
grant select, insert on table public.backtest_requests to authenticated;
grant select, update on table public.backtest_requests to service_role;
drop policy if exists "users read own backtest requests" on public.backtest_requests;
create policy "users read own backtest requests"
on public.backtest_requests for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "users create own backtest requests" on public.backtest_requests;
create policy "users create own backtest requests"
on public.backtest_requests for insert to authenticated
with check ((select auth.uid()) = user_id);
